version: '2'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      #  Put a bookmark on node_modules folder, so referenced code in container not use it outside
      - /app/node_modules # node_modules trong containter ko co reference ra ngoai
      # Map the current folder into the /app folder in container, sign : to map code /app inside container to reference outside,
      # add :cached to help docker run faster
      - web-sync:/app:cached # web-sync is an alias to use with docker-sync https://viblo.asia/p/tang-toc-do-voi-docker-sync-macos-07LKXmzJZV4
      # https://docker-sync.readthedocs.io/en/latest/getting-started/configuration.html#docker-compose-yml
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]

volumes:
  web-sync:
    external: true